#!/usr/bin/env python
from pymodbus.client.sync import ModbusTcpClient as ModbusClient

cli = ModbusClient('127.0.0.1', port=5020)
#cli = ModbusClient('192.168.1.131', port=5020)
#cli = ModbusClient('192.168.1.133', port=5020)
assert cli.connect()
#res = cli.read_input_registers(30002, count=3, unit=1)
res = cli.read_holding_registers(30001, count=1, unit=1)
assert not res.isError()
print(res.registers)
