#!/usr/bin/env python
from pymodbus.server.sync import StartTcpServer
from pymodbus.datastore import ModbusSequentialDataBlock
from pymodbus.datastore import ModbusSlaveContext, ModbusServerContext
from pymodbus.constants import Endian
from pymodbus.payload import BinaryPayloadDecoder
from pymodbus.payload import BinaryPayloadBuilder

import logging
FORMAT = ('%(asctime)-15s %(threadName)-15s'
          ' %(levelname)-8s %(module)-15s:%(lineno)-8s %(message)s')
logging.basicConfig(format=FORMAT)
log = logging.getLogger()
log.setLevel(logging.DEBUG)


def run_server():
    store = ModbusSlaveContext(
        #ir=ModbusSequentialDataBlock(30001, [152, 276, 366, 214]),
        hr=ModbusSequentialDataBlock(40000, [19]*200),
        zero_mode=True
    )
    context = ModbusServerContext(slaves=store, single=True)
    #  StartTcpServer(context, address=("localhost", 5020))
    StartTcpServer(context, address=("192.168.1.160", 5020))
    # StartTcpServer(context, address=("192.168.1.131", 5020))


if __name__ == "__main__":
    run_server()
